### ISSUE TITLE
Tokeniser doesn't explain unterminated "path-brace" tokens

### ISSUE THREAD

**Issue by flother** [borgar/fx#2]
Passing `=[Foo` to the `tokenize` function returns two tokens:

- `=`, tagged "fx-prefix"
- `[Foo`, tagged "path-brace"

But without a closing square bracket the second token isn't a valid path-brace (i.e. a workbook prefix or a structured reference). In this scenario I think it'd be nice if fx did one of two things:

1. Tags `[Foo` as two tokens, an operator (`[`) and `Foo` (an unknown token?)
2. Tags `[Foo` as one token and adds `unterminated: true` to the token, as it does with unterminated strings

I think my preference is number 2.

**Comment by borgar** [comment]
I like the second option as well for the consistency. I'm not necessarily picking this up right away so feel free to PR if you want this in.
